#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

#define LEDROT_PORT PORTB
#define LEDROT_PIN  PIN7_bm

#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN

#endif // LEDHARDWARE_H_INCLUDED
