#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

#define LEDROT_PORT PORTB
#define LEDROT_PIN  PIN7_bm

#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN

#define AUX1_PORT PORTB
#define AUX1_PIN  PIN5_bm
#define AUX1_SETUP  AUX1_PORT.DIRSET=AUX1_PIN
#define AUX1_ON     AUX1_PORT.OUTCLR=AUX1_PIN
#define AUX1_OFF    AUX1_PORT.OUTSET=AUX1_PIN
#define AUX2_PORT PORTB
#define AUX2_PIN  PIN2_bm
#define AUX2_SETUP  AUX2_PORT.DIRSET=AUX2_PIN
#define AUX2_ON     AUX2_PORT.OUTCLR=AUX2_PIN
#define AUX2_OFF    AUX2_PORT.OUTSET=AUX2_PIN
#define AUX3_PORT PORTA
#define AUX3_PIN  PIN7_bm
#define AUX3_SETUP  AUX3_PORT.DIRSET=AUX3_PIN
#define AUX3_ON     AUX3_PORT.OUTCLR=AUX3_PIN
#define AUX3_OFF    AUX3_PORT.OUTSET=AUX3_PIN
#define AUX4_PORT PORTA
#define AUX4_PIN  PIN4_bm
#define AUX4_SETUP  AUX4_PORT.DIRSET=AUX4_PIN
#define AUX4_ON     AUX4_PORT.OUTCLR=AUX4_PIN
#define AUX4_OFF    AUX4_PORT.OUTSET=AUX4_PIN

#endif // LEDHARDWARE_H_INCLUDED
