#ifndef MYCONSTANTS_H_INCLUDED
#define MYCONSTANTS_H_INCLUDED

/*
 * constants.h
 *
 * Created: 24.05.2018 19:24:50
 *  Author: chrak_2
 */


#ifndef CONSTANTS_H_
#define CONSTANTS_H_


#define BROADCAST "BR"

#define SENSOR_READY 0

// Reihenfolge, in der die Sensoren abgefragt werden
enum{KLIMASENSOR=0,TEMPSENSOREN ,LASTSENSOR};

// Ablauf der Abfrage des Sensirion-Sensors
enum{NOTHING_CLIMA_TODO=SENSOR_READY,
	START_TCONVERSION,WAIT_TCONVERSION,READ_TCONVERSION,
	START_HCONVERSION,WAIT_HCONVERSION,READ_HCONVERSION,
CALC_CONVERSION1,CALC_CONVERSION2,CALC_CONVERSION3};

// Ablauf der Abfrage der DS18B20-Sensoren
enum{NOTHING_TODO,START_CONVERSION,WAIT_CONVERSION,GET_TEMPERATURE};

enum{NOTHING_LAST_TODO=SENSOR_READY,WAIT_LAST,READY_LAST};


#define REPORT_BETWEEN_SENSORS 20   // Luecken zwischen Sensoren: 200ms
#define REPORT_BETWEEN_BLOCKS  6000 // alle 60 Sekunden

enum{TEMPREPORT=0,HUMIREPORT,ABSHUMIREPORT,DEWPOINTREPORT,DS18B20REPORT,STUFE1REPORT,STUFE2REPORT,ALARMREPORT,WATERREPORT,LASTREPORT};

#endif /* CONSTANTS_H_ */



#endif // MYCONSTANTS_H_INCLUDED
